/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicGalleryRouteImport } from './routes/_public/gallery'
import { Route as PublicGiftHistoryRouteImport } from './routes/_public/gift-history'
import { Route as PublicHeartMappingRouteImport } from './routes/_public/heart-mapping'
import { Route as PublicSpecialDaysRouteImport } from './routes/_public/special-days'
import { Route as PublicWishlistRouteImport } from './routes/_public/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminGalleryRouteImport } from './routes/admin/gallery'
import { Route as AdminGiftHistoryRouteImport } from './routes/admin/gift-history'
import { Route as AdminPlacesRouteImport } from './routes/admin/places'
import { Route as AdminSpecialDaysRouteImport } from './routes/admin/special-days'
import { Route as AdminWishlistRouteImport } from './routes/admin/wishlist'
import { Route as ApiCronSpecialDaysRouteImport } from './routes/api/cron/special-days'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGalleryRoute = PublicGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGiftHistoryRoute = PublicGiftHistoryRouteImport.update({
  id: '/gift-history',
  path: '/gift-history',
  getParentRoute: () => PublicRoute,
} as any)
const PublicHeartMappingRoute = PublicHeartMappingRouteImport.update({
  id: '/heart-mapping',
  path: '/heart-mapping',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSpecialDaysRoute = PublicSpecialDaysRouteImport.update({
  id: '/special-days',
  path: '/special-days',
  getParentRoute: () => PublicRoute,
} as any)
const PublicWishlistRoute = PublicWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => PublicRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGiftHistoryRoute = AdminGiftHistoryRouteImport.update({
  id: '/gift-history',
  path: '/gift-history',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlacesRoute = AdminPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSpecialDaysRoute = AdminSpecialDaysRouteImport.update({
  id: '/special-days',
  path: '/special-days',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWishlistRoute = AdminWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AdminRoute,
} as any)
const ApiCronSpecialDaysRoute = ApiCronSpecialDaysRouteImport.update({
  id: '/api/cron/special-days',
  path: '/api/cron/special-days',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/gallery': typeof PublicGalleryRoute
  '/gift-history': typeof PublicGiftHistoryRoute
  '/heart-mapping': typeof PublicHeartMappingRoute
  '/special-days': typeof PublicSpecialDaysRoute
  '/wishlist': typeof PublicWishlistRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/gift-history': typeof AdminGiftHistoryRoute
  '/admin/places': typeof AdminPlacesRoute
  '/admin/special-days': typeof AdminSpecialDaysRoute
  '/admin/wishlist': typeof AdminWishlistRoute
  '/admin/': typeof AdminIndexRoute
  '/api/cron/special-days': typeof ApiCronSpecialDaysRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/gallery': typeof PublicGalleryRoute
  '/gift-history': typeof PublicGiftHistoryRoute
  '/heart-mapping': typeof PublicHeartMappingRoute
  '/special-days': typeof PublicSpecialDaysRoute
  '/wishlist': typeof PublicWishlistRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/gift-history': typeof AdminGiftHistoryRoute
  '/admin/places': typeof AdminPlacesRoute
  '/admin/special-days': typeof AdminSpecialDaysRoute
  '/admin/wishlist': typeof AdminWishlistRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/api/cron/special-days': typeof ApiCronSpecialDaysRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_public/gallery': typeof PublicGalleryRoute
  '/_public/gift-history': typeof PublicGiftHistoryRoute
  '/_public/heart-mapping': typeof PublicHeartMappingRoute
  '/_public/special-days': typeof PublicSpecialDaysRoute
  '/_public/wishlist': typeof PublicWishlistRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/gift-history': typeof AdminGiftHistoryRoute
  '/admin/places': typeof AdminPlacesRoute
  '/admin/special-days': typeof AdminSpecialDaysRoute
  '/admin/wishlist': typeof AdminWishlistRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/api/cron/special-days': typeof ApiCronSpecialDaysRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/unauthorized'
    | '/gallery'
    | '/gift-history'
    | '/heart-mapping'
    | '/special-days'
    | '/wishlist'
    | '/admin/gallery'
    | '/admin/gift-history'
    | '/admin/places'
    | '/admin/special-days'
    | '/admin/wishlist'
    | '/admin/'
    | '/api/cron/special-days'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/unauthorized'
    | '/gallery'
    | '/gift-history'
    | '/heart-mapping'
    | '/special-days'
    | '/wishlist'
    | '/admin/gallery'
    | '/admin/gift-history'
    | '/admin/places'
    | '/admin/special-days'
    | '/admin/wishlist'
    | '/'
    | '/admin'
    | '/api/cron/special-days'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/login'
    | '/unauthorized'
    | '/_public/gallery'
    | '/_public/gift-history'
    | '/_public/heart-mapping'
    | '/_public/special-days'
    | '/_public/wishlist'
    | '/admin/gallery'
    | '/admin/gift-history'
    | '/admin/places'
    | '/admin/special-days'
    | '/admin/wishlist'
    | '/_public/'
    | '/admin/'
    | '/api/cron/special-days'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ApiCronSpecialDaysRoute: typeof ApiCronSpecialDaysRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/gallery': {
      id: '/_public/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof PublicGalleryRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/gift-history': {
      id: '/_public/gift-history'
      path: '/gift-history'
      fullPath: '/gift-history'
      preLoaderRoute: typeof PublicGiftHistoryRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/heart-mapping': {
      id: '/_public/heart-mapping'
      path: '/heart-mapping'
      fullPath: '/heart-mapping'
      preLoaderRoute: typeof PublicHeartMappingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/special-days': {
      id: '/_public/special-days'
      path: '/special-days'
      fullPath: '/special-days'
      preLoaderRoute: typeof PublicSpecialDaysRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/wishlist': {
      id: '/_public/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof PublicWishlistRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gift-history': {
      id: '/admin/gift-history'
      path: '/gift-history'
      fullPath: '/admin/gift-history'
      preLoaderRoute: typeof AdminGiftHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/places': {
      id: '/admin/places'
      path: '/places'
      fullPath: '/admin/places'
      preLoaderRoute: typeof AdminPlacesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/special-days': {
      id: '/admin/special-days'
      path: '/special-days'
      fullPath: '/admin/special-days'
      preLoaderRoute: typeof AdminSpecialDaysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wishlist': {
      id: '/admin/wishlist'
      path: '/wishlist'
      fullPath: '/admin/wishlist'
      preLoaderRoute: typeof AdminWishlistRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/cron/special-days': {
      id: '/api/cron/special-days'
      path: '/api/cron/special-days'
      fullPath: '/api/cron/special-days'
      preLoaderRoute: typeof ApiCronSpecialDaysRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PublicRouteChildren {
  PublicGalleryRoute: typeof PublicGalleryRoute
  PublicGiftHistoryRoute: typeof PublicGiftHistoryRoute
  PublicHeartMappingRoute: typeof PublicHeartMappingRoute
  PublicSpecialDaysRoute: typeof PublicSpecialDaysRoute
  PublicWishlistRoute: typeof PublicWishlistRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicGalleryRoute: PublicGalleryRoute,
  PublicGiftHistoryRoute: PublicGiftHistoryRoute,
  PublicHeartMappingRoute: PublicHeartMappingRoute,
  PublicSpecialDaysRoute: PublicSpecialDaysRoute,
  PublicWishlistRoute: PublicWishlistRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminGiftHistoryRoute: typeof AdminGiftHistoryRoute
  AdminPlacesRoute: typeof AdminPlacesRoute
  AdminSpecialDaysRoute: typeof AdminSpecialDaysRoute
  AdminWishlistRoute: typeof AdminWishlistRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGalleryRoute: AdminGalleryRoute,
  AdminGiftHistoryRoute: AdminGiftHistoryRoute,
  AdminPlacesRoute: AdminPlacesRoute,
  AdminSpecialDaysRoute: AdminSpecialDaysRoute,
  AdminWishlistRoute: AdminWishlistRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ApiCronSpecialDaysRoute: ApiCronSpecialDaysRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
